/// @description Variables

//State variables

enum CARDINALNOCTISCONGRATS 
{
	LAVENDER_GREETING,
	LAVENDER_ASCEND,
	LAVENDER_CALL_ASSEMBLY,
	AUDIENCE_ASSEMBLE,
	LAVENDER_SPEECH,
	AUDIENCE_CHEER,
	LAVENDER_END_SPEECH,
	SHRINE_EXPLOSION,
	AUDIENCE_PANIC,
	LAVENDER_ORDERS,
	LAVENDER_DESCEND,
	LAVENDER_LAST_SPEECH,
	LAVENDER_LEAVE
}

CardinalNoctisCongrats_State = 0;
