sprite_index = spr_NPC_NoxCity_FloatLady;

Name = "Fanna";

Speech = 
[
	"I MAY BE TRAPPED UNDERGROUND! BUT MY WINGS WILL NOT BE CLIPPED",
	"THE NOXIANS DESIRE FREEDOM! NONE SHALL TAKE IT FROM US!",
	"CARDINAL! LET THE WISDOM OF THE STARS AND SKIES GUIDE YOU!"
];